sonar.projectKey=symfony-demo-client
sonar.projectName=Symfony Demo Client
sonar.language=php
sonar.sources=src
sonar.tests=tests
sonar.php.coverage.reportPaths=coverage.xml
sonar.exclusions=vendor/**